---
- debug: msg="Ssh port {{ SSH_PORT }}"

- name: change ssh port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Port"
    line: "Port {{ SSH_PORT }}"
  notify:
   - restart ssh redhat
   - restart ssh debian

- name: disallow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
  notify:
   - restart ssh redhat
   - restart ssh debian

- name: Comment PasswordAuthentication yes if present
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    replace: '#PasswordAuthentication yes'
  notify:
   - restart ssh redhat
   - restart ssh debian

- name: disallow root SSH access
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PermitRootLogin no"
  notify:
   - restart ssh redhat
   - restart ssh debian

- name: Comment PermitRootLogin yes if present
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes'
    replace: '#PermitRootLogin yes'
  notify:
   - restart ssh redhat
   - restart ssh debian
