---
- name: upgrade all packages on Red Hat system
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: upgrade APT to the latest packages
  apt:
    upgrade: safe
  when: ansible_os_family == "Debian"